# Generated by Django 4.1.7 on 2023-04-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_apps', '0005_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assigned_to_email',
            field=models.CharField(default='forbushs@bc.edu', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='app',
            name='office_hours',
            field=models.CharField(max_length=15),
        ),
    ]
