# Generated by Django 4.1.7 on 2023-03-22 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_apps', '0005_course_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='assigned_to',
        ),
    ]
