# Generated by Django 4.1.7 on 2023-04-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_apps', '0006_course_assigned_to_email_alter_app_office_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='num_uses',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
