# Generated by Django 4.1.7 on 2023-04-19 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('view_apps', '0007_app_num_uses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='eagle_id',
        ),
        migrations.RemoveField(
            model_name='app',
            name='major',
        ),
        migrations.RemoveField(
            model_name='app',
            name='student_name',
        ),
        migrations.AddField(
            model_name='app',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='app',
            name='course_id',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='app',
            name='num_uses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='app',
            name='office_hours',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='app',
            name='why_ta',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
