# Generated by Django 4.1.7 on 2023-04-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_apps', '0008_remove_app_eagle_id_remove_app_major_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='course_id',
        ),
        migrations.AddField(
            model_name='course',
            name='applications',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
