# Generated by Django 4.1.7 on 2023-04-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_apps', '0010_alter_app_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='app_id',
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
