# Generated by Django 4.1.7 on 2023-04-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_apps', '0016_alter_app_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assigned_students',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='app',
            name='id',
            field=models.CharField(default='32697397', max_length=1000, primary_key=True, serialize=False),
        ),
    ]
