# Generated by Django 4.1.7 on 2023-04-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_apps', '0017_course_assigned_students_alter_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='id',
            field=models.CharField(default='20105623', max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='assigned_students',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
