# Generated by Django 4.1.7 on 2023-04-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_apps', '0020_course_num_assigned_alter_app_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='id',
            field=models.CharField(default='66522787', max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='applications',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
