# Generated by Django 4.1.7 on 2023-04-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_apps', '0021_course_is_open_alter_app_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='accepted_students',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='app',
            name='id',
            field=models.CharField(default='50528302', max_length=1000, primary_key=True, serialize=False),
        ),
    ]
