# Generated by Django 4.1.7 on 2023-04-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("view_apps", "0023_course_num_accepted_alter_app_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="id",
            field=models.CharField(
                default="51167826", max_length=1000, primary_key=True, serialize=False
            ),
        ),
    ]
