# Generated by Django 4.1.7 on 2023-05-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_apps', '0028_alter_app_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='email_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='app',
            name='student_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='email_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='app',
            name='id',
            field=models.CharField(default='43005393', max_length=1000, primary_key=True, serialize=False),
        ),
    ]
