# Generated by Django 4.1.7 on 2023-05-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_apps', '0029_app_email_text_app_student_text_course_email_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='id',
            field=models.CharField(default='24243228', max_length=1000, primary_key=True, serialize=False),
        ),
    ]
