# Generated by Django 4.2.1 on 2023-05-15 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("view_apps", "0032_alter_app_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "name",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("start", models.DateField()),
                ("end", models.DateField()),
                ("open", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="app",
            name="id",
            field=models.CharField(
                default="64393985", max_length=1000, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="semester",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="view_apps.semester",
            ),
        ),
    ]
