# Generated by Django 4.2.1 on 2023-05-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("view_apps", "0036_alter_app_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="id",
            field=models.CharField(
                default="15557851", max_length=1000, primary_key=True, serialize=False
            ),
        ),
    ]
