# Generated by Django 4.1.7 on 2023-05-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_apps', '0036_alter_app_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.AlterField(
            model_name='app',
            name='id',
            field=models.CharField(default='81153065', max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
