# Generated by Django 4.1.7 on 2023-05-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_apps', '0037_remove_course_semester_alter_app_id_delete_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('open', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='app',
            name='id',
            field=models.CharField(default='91654863', max_length=1000, primary_key=True, serialize=False),
        ),
    ]
