# Generated by Django 4.1.7 on 2023-04-04 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("login", "0002_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stud_profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.TextField(blank=True, max_length=60)),
                ("last_name", models.TextField(blank=True, max_length=60)),
                ("email", models.EmailField(blank=True, max_length=60)),
                ("grad_class", models.DateField()),
                ("school", models.TextField(blank=True, max_length=10)),
                ("major", models.TextField(blank=True, max_length=60)),
                ("minors", models.TextField(blank=True, max_length=200)),
                ("blurb", models.TextField(blank=True, max_length=500)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prof_profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.TextField(blank=True, max_length=60)),
                ("last_name", models.TextField(blank=True, max_length=60)),
                ("department", models.TextField(blank=True, max_length=60)),
                ("email", models.EmailField(blank=True, max_length=60)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
