# Generated by Django 4.1.7 on 2023-04-04 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stud_profile",
            name="grad_class",
        ),
    ]
