# Generated by Django 4.1.7 on 2023-04-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0004_remove_stud_profile_grad_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prof_profile",
            name="department",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="prof_profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="prof_profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="stud_profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="stud_profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="stud_profile",
            name="major",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="stud_profile",
            name="minors",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="stud_profile",
            name="school",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
