# Generated by Django 4.1.7 on 2023-04-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_admin_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_profile',
        ),
    ]
