# Generated by Django 4.1.7 on 2023-04-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_stud_profile_major_remove_stud_profile_minors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud_profile',
            name='currently_hired',
            field=models.BooleanField(default=False),
        ),
    ]
